"use client";
import React, {
  useMemo,
  useState,
  useEffect,
  useCallback,
} from "react";
import { Table } from "@/app/admin/tables-essentials/Tables";
import { Modal } from "@/app/shared/Modal";
import { reports } from "@/app/api/super-admin/reports";
import Image from "next/image";
import Drawer from "./Drawer";
import { ReportItem } from "@/app/api/super-admin/reports/types";
import { toast } from "react-hot-toast";
import FilterDrawer from "@/app/admin/tables-essentials/Filter";

interface CertificationData {
  [key: string]: string;
  // "Report ID": string;
  "Report Type": string;
  "Date Range": string;
  "Generated Date": string;
  "Generated By": string;
  Format: string;
}

interface ReportStats {
  total: number;
  active: number;
  expired: number;
  revoked: number;
}

interface ReportParams {
  search?: string;
  reportType?: "WEEKLY" | "MONTHLY" | "CUSTOM" | "ALL";
  certificationStatus?: "ALL" | "ACTIVE" | "EXPIRED" | "REVOKED";
  generatedDateTo?: string;
  // Pagination
  page?: number;
  pageSize?: number;
  // Some APIs may use `limit` instead of `pageSize`
  limit?: number;
}

interface CredentialItem {
  id: number;
  img: string;
  val: number;
  title: string;
}

interface PaginationData {
  total: number;
  pageSize: number;
  currentPage: number;
  totalPages: number;
  nextPage: number | null;
  prevPage: number | null;
  hasNextPage: boolean;
  hasPrevPage: boolean;
}

export default function Reports() {
  const [isFilterOpen, setIsFilterOpen] = useState<boolean>(false);
  const [isExportDrawerOpen, setIsExportDrawerOpen] = useState<boolean>(false);
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [debouncedSearchTerm, setDebouncedSearchTerm] = useState<string>("");
  const [currentPage, setCurrentPage] = useState<number>(1);
  const [itemsPerPage] = useState<number>(10);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [data, setData] = useState<ReportStats>({
    total: 0,
    active: 0,
    expired: 0,
    revoked: 0,
  });

  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [selectedRows, setSelectedRows] = useState<Set<string>>(new Set());
  const [singleRowToDelete, setSingleRowToDelete] = useState<{
    row: Record<string, string>;
    id: string;
  } | null>(null);
  const [modalType, setModalType] = useState<"single" | "multiple">("multiple");

  const [showReportTypeDropdown, setShowReportTypeDropdown] = useState<boolean>(false);
  const [showStatusDropdown, setShowStatusDropdown] = useState<boolean>(false);

  const [appliedFilters, setAppliedFilters] = useState({
    reportType: "",
    certificationStatus: "",
    generatedDateTo: "",
  });

  const [tempFilters, setTempFilters] = useState({
    reportType: "",
    certificationStatus: "",
    generatedDateTo: "",
  });

  const [generatedDate, setGeneratedDate] = useState<Date | null>(null);

  const [allReportsData, setAllReportsData] = useState<ReportItem[]>([]);
  const [paginationData, setPaginationData] = useState<PaginationData>({
    total: 0,
    pageSize: 10,
    currentPage: 1,
    totalPages: 1,
    nextPage: null,
    prevPage: null,
    hasNextPage: false,
    hasPrevPage: false,
  });

  const [allReportTypes, setAllReportTypes] = useState<string[]>([]);
  const [allCertificationStatuses, setAllCertificationStatuses] = useState<string[]>([]);

  // Debounce search term - only update if 3+ characters or empty
  useEffect(() => {
    const handler = setTimeout(() => {
      if (searchTerm.trim().length >= 3 || searchTerm.trim() === "") {
        setDebouncedSearchTerm(searchTerm);
      }
    }, 500);

    return () => {
      clearTimeout(handler);
    };
  }, [searchTerm]);

  const hasActiveFilters = useMemo(() => {
    return (
      debouncedSearchTerm.trim() !== "" ||
      appliedFilters.reportType.trim() !== "" ||
      appliedFilters.certificationStatus.trim() !== "" ||
      appliedFilters.generatedDateTo !== ""
    );
  }, [debouncedSearchTerm, appliedFilters]);

  const Credentials: CredentialItem[] = [
    {
      id: 1,
      img: "/images/ravanue.svg",
      val: data.total,
      title: "Total Issued Certificates",
    },
    {
      id: 2,
      img: "/images/manager.svg",
      val: data.active,
      title: "Active Certificates",
    },
    {
      id: 3,
      img: "/images/certificate.svg",
      val: data.expired,
      title: "Expired Certificates",
    },
    {
      id: 4,
      img: "/images/p-app.svg",
      val: data.revoked,
      title: "Revoked Certificates",
    },
  ];

  // Fetch filter options
  const fetchFilterOptions = useCallback(async () => {
    try {
      const response = await reports.getReports({});

      if (response.success && response.data) {
        const reportsData = response.data.reports;

        const reportTypes = [
          ...new Set(reportsData.map((report) => report.reportType || ""))
        ].filter(Boolean);

        const certificationStatuses = [
          ...new Set(reportsData.map((report) => report.certificationStatus || ""))
        ].filter(Boolean);

        setAllReportTypes(reportTypes);
        setAllCertificationStatuses(certificationStatuses);
      }
    } catch (error) {
      console.error("Error fetching filter options:", error);
    }
  }, []);

  useEffect(() => {
    fetchFilterOptions();
  }, [fetchFilterOptions]);

  useEffect(() => {
    if (isFilterOpen) {
      setTempFilters(appliedFilters);
      if (appliedFilters.generatedDateTo) {
        setGeneratedDate(new Date(appliedFilters.generatedDateTo));
      } else {
        setGeneratedDate(null);
      }
    }
  }, [isFilterOpen, appliedFilters]);

  const formatDateForAPI = (date: Date | null): string => {
    if (!date) return "";
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  };

  // Fetch reports from API
  const fetchReports = useCallback(async (): Promise<void> => {
    try {
      setIsLoading(true);

      const queryParams: ReportParams = {};

      if (!hasActiveFilters) {
        // Only add pagination when no active filters
        queryParams.page = currentPage;
        queryParams.pageSize = itemsPerPage;
      } else {
        // With filters, only add pagination if not first page
        if (currentPage > 1) {
          queryParams.page = currentPage;
        }
        if (itemsPerPage !== 10) {
          queryParams.pageSize = itemsPerPage;
        }
      }

      // Only include search if it has 3+ characters
      if (debouncedSearchTerm.trim().length >= 3) {
        queryParams.search = debouncedSearchTerm.trim();
      }

      if (appliedFilters.reportType.trim()) {
        queryParams.reportType = appliedFilters.reportType.trim() as "WEEKLY" | "MONTHLY" | "CUSTOM" | "ALL";
      }

      if (appliedFilters.certificationStatus.trim()) {
        queryParams.certificationStatus = appliedFilters.certificationStatus.trim() as "ALL" | "ACTIVE" | "EXPIRED" | "REVOKED";
      }

      if (appliedFilters.generatedDateTo) {
        queryParams.generatedDateTo = appliedFilters.generatedDateTo;
      }

      console.log("🚀 HITTING REPORTS API WITH PARAMS:", queryParams);

      const response = await reports.getReports(queryParams);

      if (response.success && response.data) {
        // Normalize response.data into a local shape that may include either
        // a `pagination` object or individual pagination fields (page, limit, totalPages)
        const respData = response.data as unknown as {
          reports?: ReportItem[];
          pagination?: PaginationData;
          total?: number;
          meta?: { total?: number };
          page?: number;
          limit?: number;
          totalPages?: number;
        };

        setAllReportsData(respData.reports || []);

        if (respData.pagination) {
          setPaginationData(respData.pagination);
        } else {
          // Fallback pagination calculation
          const total = respData.total || respData.meta?.total || 0;
          const totalPages = Math.ceil(total / itemsPerPage);
          setPaginationData({
            total,
            pageSize: itemsPerPage,
            currentPage,
            totalPages,
            nextPage: currentPage < totalPages ? currentPage + 1 : null,
            prevPage: currentPage > 1 ? currentPage - 1 : null,
            hasNextPage: currentPage < totalPages,
            hasPrevPage: currentPage > 1,
          });
        }
      } else {
        console.error("❌ Unexpected response:", response);
        setAllReportsData([]);
        setPaginationData({
          total: 0,
          pageSize: itemsPerPage,
          currentPage: 1,
          totalPages: 1,
          nextPage: null,
          prevPage: null,
          hasNextPage: false,
          hasPrevPage: false,
        });
      }
    } catch (error) {
      console.error("🚨 Error fetching reports:", error);
      toast.error("Failed to fetch reports");
      setAllReportsData([]);
      setPaginationData({
        total: 0,
        pageSize: itemsPerPage,
        currentPage: 1,
        totalPages: 1,
        nextPage: null,
        prevPage: null,
        hasNextPage: false,
        hasPrevPage: false,
      });
    } finally {
      setIsLoading(false);
    }
  }, [
    debouncedSearchTerm,
    appliedFilters.reportType,
    appliedFilters.certificationStatus,
    appliedFilters.generatedDateTo,
    currentPage,
    itemsPerPage,
    hasActiveFilters,
  ]);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  const fetchStats = useCallback(async (): Promise<void> => {
    try {
      const response = await reports.getReportStats();
      if (response.data) {
        setData(response.data);
      }
    } catch (error) {
      console.error("Error fetching stats:", error);
    }
  }, []);

  // Fetch stats on mount
  useEffect(() => {
    void fetchStats();
  }, [fetchStats]);

  // Transform API data to display format
  const displayData: CertificationData[] = useMemo(() => {
    return allReportsData.map((report) => {
      const startDate = new Date(report.startDate).toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
      });
      const endDate = new Date(report.endDate).toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
      });
      const generatedDate = new Date(report.generatedAt).toLocaleDateString(
        "en-US",
        {
          month: "short",
          day: "numeric",
          year: "numeric",
        }
      );

      // Extract file extension from fileName
      const fileExtension = report.fileName.split(".").pop()?.toUpperCase() || "PDF";

      return {
        // "Report ID": report.id,
        "Report Type": report.reportType,
        "Date Range": `${startDate} - ${endDate}`,
        "Generated Date": generatedDate,
        "Generated By": report.generatedByUser.name,
        Format: fileExtension,
      };
    });
  }, [allReportsData]);

  const handleSelectAll = (checked: boolean) => {
    const newSelected = new Set(selectedRows);
    if (checked) {
      allReportsData.forEach((item) => newSelected.add(item.id));
    } else {
      allReportsData.forEach((item) => newSelected.delete(item.id));
    }
    setSelectedRows(newSelected);
  };

  const handleSelectRow = (id: string, checked: boolean) => {
    const newSelected = new Set(selectedRows);
    if (checked) {
      newSelected.add(id);
    } else {
      newSelected.delete(id);
    }
    setSelectedRows(newSelected);
  };

  const isAllDisplayedSelected = useMemo(() => {
    return (
      allReportsData.length > 0 &&
      allReportsData.every((item) => selectedRows.has(item.id))
    );
  }, [allReportsData, selectedRows]);

  const isSomeDisplayedSelected = useMemo(() => {
    return (
      allReportsData.some((item) => selectedRows.has(item.id)) &&
      !isAllDisplayedSelected
    );
  }, [allReportsData, selectedRows, isAllDisplayedSelected]);

  // Delete multiple reports
  const handleDeleteReports = async (selectedRowIds: Set<string>) => {
    try {
      setIsLoading(true);
      const deletePromises = Array.from(selectedRowIds).map((id) =>
        reports.deleteReport(id)
      );

      await Promise.all(deletePromises);
      toast.success("Reports deleted successfully");
      
      await fetchReports();
      setIsModalOpen(false);
      setSelectedRows(new Set());
    } catch (error) {
      console.error("Error deleting reports:", error);
      toast.error("Failed to delete reports");
    } finally {
      setIsLoading(false);
    }
  };

  // Delete single report
  const handleDeleteSingleReport = async (id: string) => {
    try {
      setIsLoading(true);
      await reports.deleteReport(id);
      toast.success("Report deleted successfully");
      
      await fetchReports();
      setIsModalOpen(false);
      setSingleRowToDelete(null);
      
      // Remove from selected rows if present
      const newSelected = new Set(selectedRows);
      newSelected.delete(id);
      setSelectedRows(newSelected);
    } catch (error) {
      console.error("Error deleting report:", error);
      toast.error("Failed to delete report");
    } finally {
      setIsLoading(false);
    }
  };

  const openDeleteSingleModal = (row: Record<string, string>, id: string) => {
    setSingleRowToDelete({ row, id });
    setModalType("single");
    setIsModalOpen(true);
  };

  const handleDeleteSelected = () => {
    if (selectedRows.size > 0) {
      setModalType("multiple");
      setIsModalOpen(true);
    }
  };

  const handleModalConfirm = () => {
    if (modalType === "multiple" && selectedRows.size > 0) {
      handleDeleteReports(selectedRows);
    } else if (modalType === "single" && singleRowToDelete) {
      handleDeleteSingleReport(singleRowToDelete.id);
    }
  };

  // Download report
  const handleDownloadReport = useCallback(async (reportId: string): Promise<void> => {
    try {
      setIsLoading(true);
      const response = await reports.reDownloadReport(reportId);

      if (response.success && response.data) {
        const { filePath, fileName } = response.data;

        if (filePath) {
          // Open report in a new tab
          window.open(filePath, "_blank");
          toast.success(`${fileName || "Report"} downloaded successfully`);
        } else {
          toast.error("File path not found in response");
        }
      } else {
        toast.error("Failed to re-download report");
      }
    } catch (error) {
      console.error("Error re-downloading report:", error);
      toast.error("Failed to re-download report");
    } finally {
      setIsLoading(false);
    }
  }, []);

  const tableControl = {
    hover: true,
  };

  useEffect(() => {
    setCurrentPage(1);
  }, [
    debouncedSearchTerm,
    appliedFilters.reportType,
    appliedFilters.certificationStatus,
    appliedFilters.generatedDateTo,
  ]);

  const handleResetFilter = () => {
    const resetFilters = {
      reportType: "",
      certificationStatus: "",
      generatedDateTo: "",
    };

    setTempFilters(resetFilters);
    setAppliedFilters(resetFilters);
    setGeneratedDate(null);
    setSearchTerm("");
    setDebouncedSearchTerm("");
    setCurrentPage(1);
    setIsFilterOpen(false);
  };

  const handleApplyFilter = () => {
    const dateString = formatDateForAPI(generatedDate);

    const filtersToApply = {
      reportType: tempFilters.reportType,
      certificationStatus: tempFilters.certificationStatus,
      generatedDateTo: dateString,
    };

    console.log("🟢 APPLYING REPORTS FILTERS:", filtersToApply);

    setAppliedFilters(filtersToApply);
    setCurrentPage(1);
    setIsFilterOpen(false);
  };

  const handleCloseFilter = () => {
    setTempFilters(appliedFilters);
    if (appliedFilters.generatedDateTo) {
      setGeneratedDate(new Date(appliedFilters.generatedDateTo));
    } else {
      setGeneratedDate(null);
    }
    setIsFilterOpen(false);
  };

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };

  const handleSearch = (term: string) => {
    setSearchTerm(term);
    // Only reset page if we're actually going to search (3+ chars) or clearing search
    if (term.trim().length >= 3 || term.trim() === "") {
      setCurrentPage(1);
    }
  };

  const dropdownItems = [
    {
      label: "Download Report",
      onClick: (row: Record<string, string>, index: number) => {
        const originalRow = allReportsData[index];
        if (originalRow) {
          handleDownloadReport(originalRow.id);
        } else {
          console.error("🔴 Could not find original row for index:", index);
        }
      },
    },
    {
      label: "Delete Report",
      onClick: (row: Record<string, string>, index: number) => {
        const originalRow = allReportsData[index];
        if (originalRow) {
          openDeleteSingleModal(row, originalRow.id);
        } else {
          console.error("🔴 Could not find original row for index:", index);
        }
      },
    },
  ];

  if (isLoading && allReportsData.length === 0) {
    return (
      <div className="flex items-center justify-center h-64">
        <p className="text-white">Loading reports...</p>
      </div>
    );
  }

  return (
    <>
      {isModalOpen && (
        <Modal
          isOpen={isModalOpen}
          onClose={() => {
            setIsModalOpen(false);
            setSelectedRows(new Set());
            setSingleRowToDelete(null);
          }}
          onConfirm={handleModalConfirm}
          title="Confirm Report Deletion"
          description="Deleting this report means it will no longer appear in your reports list."
          image="/images/delete-modal.png"
          confirmText="Delete"
        />
      )}

      {/* Enhanced Export Drawer with Smooth Animation */}
      <div
        className={`fixed inset-0 z-[2000] transition-all duration-300 ease-in-out ${
          isExportDrawerOpen ? "opacity-100 visible" : "opacity-0 invisible"
        }`}
      >
        {/* Backdrop */}
        <div
          className={`absolute inset-0 bg-black transition-opacity duration-300 ease-in-out ${
            isExportDrawerOpen ? "opacity-50" : "opacity-0"
          }`}
          onClick={() => setIsExportDrawerOpen(false)}
        />

        {/* Drawer */}
        <div
          className={`absolute right-0 top-0 h-full transform transition-transform duration-300 ease-in-out ${
            isExportDrawerOpen ? "translate-x-0" : "translate-x-full"
          }`}
        >
          <Drawer
            onClose={() => setIsExportDrawerOpen(false)}
            onReportCreated={fetchReports}
          />
        </div>
      </div>

      <div className="flex flex-col gap-3 sm:flex-row sm:gap-0 justify-between items-center">
        <div>
          <h2 className="font-semibold text-[20px] leading-[20px]">
            Report & Analytics
          </h2>
          <p className="font-regular text-[16px] leading-5 mb-[22px] pt-2 text-[#FFFFFF99]">
            Generate insights and export certification data for compliance and
            record-keeping.
          </p>
        </div>

        <button
          className="py-3 px-5 yellow-btn text-[#121315] font-semibold text-[16px] leading-5 transition-all duration-200 hover:scale-105"
          onClick={() => setIsExportDrawerOpen(true)}
          type="button"
        >
          Export Report
        </button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 pt-5 flex-wrap lg:flex-nowrap justify-between">
        {Credentials.map((item) => (
          <div key={item.id} className="gap-3">
            <div className="flex items-center bg-[#121315] rounded-xl gap-4 p-5">
              <Image 
                src={item.img} 
                alt={item.title} 
                width={48} 
                height={48} 
                priority
              />
              <div>
                <h2 className="font-medium text-[18px] leading-[22px] text-white">
                  {item.val}
                </h2>
                <p className="text-white/80 font-normal text-[14px] leading-[18px] pt-2  ">
                  {item.title}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="flex flex-col justify-between mt-5">
        <Table
          data={displayData}
          title="Reports"
          control={tableControl}
          showDeleteButton={true}
          onDeleteSingle={(row, index) => {
            const originalRow = allReportsData[index];
            if (originalRow) {
              openDeleteSingleModal(row, originalRow.id);
            } else {
              console.error("🔴 Could not find original row for index:", index);
            }
          }}
          showPagination={true}
          clickable={true}
          selectedRows={selectedRows}
          setSelectedRows={setSelectedRows}
          onSelectAll={handleSelectAll}
          onSelectRow={handleSelectRow}
          isAllSelected={isAllDisplayedSelected}
          isSomeSelected={isSomeDisplayedSelected}
          rowIds={allReportsData.map((item) => item.id)}
          dropdownItems={dropdownItems}
          searchTerm={searchTerm}
          onSearchChange={handleSearch}
          currentPage={currentPage}
          onPageChange={handlePageChange}
          itemsPerPage={paginationData.pageSize}
          totalItems={paginationData.total || 0}
          showFilter={true}
          onFilterToggle={setIsFilterOpen}
          onDeleteAll={handleDeleteSelected}
          isDeleteAllDisabled={
            selectedRows.size === 0 || selectedRows.size < displayData.length
          }
          disableClientSidePagination={true}
        />
      </div>

      <FilterDrawer
        isOpen={isFilterOpen}
        onClose={handleCloseFilter}
        title="Filter Reports"
        description="Refine reports to find the specific data you need."
        resetLabel="Reset"
        onReset={handleResetFilter}
        buttonLabel="Apply Filter"
        onApply={handleApplyFilter}
        filterValues={{
          reportType: tempFilters.reportType,
          certificationStatus: tempFilters.certificationStatus,
          "Generated on": generatedDate,
        }}
        onFilterChange={(newValues) => {
          if (newValues.reportType !== undefined) {
            setTempFilters((prev) => ({
              ...prev,
              reportType: newValues.reportType as string,
            }));
          }
          if (newValues.certificationStatus !== undefined) {
            setTempFilters((prev) => ({
              ...prev,
              certificationStatus: newValues.certificationStatus as string,
            }));
          }
          if (newValues["Generated on"] !== undefined) {
            setGeneratedDate(newValues["Generated on"] as Date | null);
          }
        }}
        dropdownStates={{
          reportType: showReportTypeDropdown,
          certificationStatus: showStatusDropdown,
        }}
        onDropdownToggle={(key, value) => {
          if (key === "reportType") setShowReportTypeDropdown(value);
          if (key === "certificationStatus") setShowStatusDropdown(value);
        }}
        fields={[
          {
            label: "Report Type",
            key: "reportType",
            type: "dropdown",
            placeholder: "Select type",
            options: allReportTypes,
          },
          {
            label: "Certification Status",
            key: "certificationStatus",
            type: "dropdown",
            placeholder: "Select status",
            options: allCertificationStatuses,
          },
          {
            label: "Generated on",
            key: "Generated on",
            type: "date",
            placeholder: "Select date",
          },
        ]}
      />
    </>
  );
}