import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Manrope } from "next/font/google";
import GlobalAuthManager from "./shared/utils/auth-guard/AuthGuard";
import { Providers } from "./google-login/Provider";
import Script from "next/script";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Rental Host",
  description: "Generated by Vordx",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="beforeInteractive"
        />
      </head>

      <body className={`${manrope.className} !overflow-x-hidden`}>
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 1000,
            style: {
              background: "white",
              color: "black",
              zIndex:"9000000000"
            },
            success: {
              duration: 1000,
            },
          }}
        />
        <GlobalAuthManager />

        <main>
          {/* REMOVED: GoogleOAuthProvider since we're using manual GSI */}
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}